export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_CURRENT_DATE_TIME = 'GET_CURRENT_DATE_TIME';
export const GET_CURRENT_DIRECTORY = 'GET_CURRENT_DIRECTORY';